#It probably suck but I want to try
name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Build project
      run: cargo build --release

    - name: Run tests
      run: cargo test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nightly-build
        path: target/release/
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-$(date +'%Y%m%d')
        release_name: Nightly Build - $(date +'%Y-%m-%d')
        draft: false
        prerelease: true
