name: Rust CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v2
        with:
          rust-version: '1.80.1'

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --release

      - name: Create Release
        if: success() && github.event_name == 'push'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'v${{ github.run_number }}'
          release_name: 'Auto Release v${{ github.run_number }}'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        if: success() && github.event_name == 'push'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/CrabMC
          asset_name: CrabMC
          asset_content_type: application/octet-stream
